/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tech.cathywu.excelreader;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
