/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tech.cathywu.excelreader;

import org.junit.Test;

import static org.junit.Assert.*;

public class ApplicationTest {
    @Test
    public void testSomeLibraryMethod() {
    }
}
